dateModified: 1785081142
meta:
  __names__:
    ae137db2-05c9-46be-ab1d-89115bb8ab4e: 'Craft in Laravel' # Craft in Laravel
    d4c48fb1-b001-4ef4-bd18-6fb4f6a80248: 'Craft in Laravel' # Craft in Laravel
system:
  edition: solo
  live: true
  name: 'Craft in Laravel'
  schemaVersion: 6.0.0.4
  timeZone: $TZ
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
